### ISSUE TITLE
Support ygot generator installed with go install

### ISSUE THREAD

**Issue by tokarenko** [andresterba/go-ygot-generator-generator#3]
Thank you for the generator. I am unable to use it with ygot generator installed with `go install`:
```shell
go install github.com/andresterba/go-ygot-generator-generator@latest
go install github.com/openconfig/ygot/generator@latest
go-ygot-generator-generator ygot-generator.yaml yang-openconfig.go
```

No error and no result.

Configuration:
```yaml
---
generator_options:
  - option: output_file
    value: ./yang.go
  - option: include_model_data
    value: true
  - option: generate_fakeroot
    value: true
  - option: fakeroot_name
    value: device
  - option: exclude_modules
    value: ietf-interfaces
models:
  - openconfig-system.yang
  - openconfig-interfaces.yang
  - openconfig-if-ethernet.yang
path_to_generator: generator
path_to_models: ./yang
```
